### ISSUE TITLE
No module name cv

### ISSUE THREAD

**Issue by Danish22** [RobinDavid/Motion-detection-OpenCV#3]
![cv](https://cloud.githubusercontent.com/assets/8232132/13420554/442435e8-dfad-11e5-8052-449d61d70f65.JPG)

**Comment by lexi123** [comment]
I have the same problem. any suggestions please?

**Comment by alciomarhollanda** [comment]
cv2.cv has been removed in OpenCV3 and functions have changed

And this is OpenCV Documention:http://opencv.org/documentation.html

**Comment by W0x404** [comment]
1) Use Ubuntu ( 16.04 is preferable )
2) sudo apt-get install python-opencv
3) ...
4) Enjoy.

**Comment by RobinDavid** [comment]
Yes I am using the old cv bindings. I will update it, when I will have time.
