### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by AnotherAnkor** [RobinDavid/Motion-detection-OpenCV#5]
Debian 8.
`python: /build/libav-6imAXN/libav-11.9/libavformat/asfenc.c:858: asf_write_packet: Assertion `pts != 0x8000000000000000L' failed.
`
All given files have size 521 Kb.
What should I do?
Tnx!

**Comment by RobinDavid** [comment]
I guess, you have an issue with the python binding version and the debian libopencv. Apart from that no idea..
